### ISSUE TITLE
Not support k8s 1.22

### ISSUE THREAD

**Issue by life-learner1** [knative-sandbox/eventing-awssqs#177]
**Describe the bug**

 **Expected behavior**

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by odacremolbap** [comment]
https://github.com/knative-sandbox/eventing-awssqs/pull/178
@lionelvillard ^^

@life-learner1 we bundled the AWS SQS Source with a lot of other components to simplify usage/release.

**Comment by life-learner1** [comment]
Thank you, I fixed this isusse, will  migrate to triggermesh later
