### ISSUE TITLE
No matches for kind "ServiceEntry" in version "networking.istio.io/v1alpha3"

### ISSUE THREAD

**Issue by houshengbo** [knative-sandbox/eventing-awssqs#97]
**Describe the bug**
```
no matches for kind \"ServiceEntry\" in version \"networking.istio.io/v1alpha3\"","stacktrace":"knative.dev/operator/pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing.(*reconcilerImpl).Reconcile\n\tknative.dev/operator/pkg/client/injection/reconciler/operator/v1alpha1/knativeeventing/reconciler.go:300\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210602095030-0e61d6763dd6/controller/controller.go:531\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210602095030-0e61d6763dd6/controller/controller.go:468"}
```

 **Expected behavior**
No error for installation.

 **To Reproduce**
Install the Amazon SQS source: https://github.com/knative-sandbox/eventing-awssqs/releases/download/v0.23.0/awssqs.yaml

 **Knative release version**
All, including 0.23

 **Additional context**
Related issue: https://github.com/knative/operator/issues/646

**Comment by evankanderson** [comment]
This seems to assume that Istio is present; it would be good to release an istio-not-required manifest as well.
